export enum ActionType {
    getAllCoupons,
    getCouponsByPage,
    getCouponsSortedBy,
    openModal,
    getCouponById,
    createCustomer,
    getCouponsByCategory,
    isLoggedIn,
    getPurchaseId,
    getPurchaseDetails,
    getAllPurchasesDetails,
    getAllPurchasesDetailsByPage,
    getAllCompanies,
    getCompaniesByPage,
    getCompanyById,
    getPageNumber,
    getCouponsByCompanyId
}